// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"qr_backend/ent/filereference"
	"qr_backend/ent/predicate"
	"qr_backend/ent/qrcode"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FileReferenceQuery is the builder for querying FileReference entities.
type FileReferenceQuery struct {
	config
	ctx        *QueryContext
	order      []filereference.OrderOption
	inters     []Interceptor
	predicates []predicate.FileReference
	withQrCode *QRCodeQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FileReferenceQuery builder.
func (frq *FileReferenceQuery) Where(ps ...predicate.FileReference) *FileReferenceQuery {
	frq.predicates = append(frq.predicates, ps...)
	return frq
}

// Limit the number of records to be returned by this query.
func (frq *FileReferenceQuery) Limit(limit int) *FileReferenceQuery {
	frq.ctx.Limit = &limit
	return frq
}

// Offset to start from.
func (frq *FileReferenceQuery) Offset(offset int) *FileReferenceQuery {
	frq.ctx.Offset = &offset
	return frq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (frq *FileReferenceQuery) Unique(unique bool) *FileReferenceQuery {
	frq.ctx.Unique = &unique
	return frq
}

// Order specifies how the records should be ordered.
func (frq *FileReferenceQuery) Order(o ...filereference.OrderOption) *FileReferenceQuery {
	frq.order = append(frq.order, o...)
	return frq
}

// QueryQrCode chains the current query on the "qr_code" edge.
func (frq *FileReferenceQuery) QueryQrCode() *QRCodeQuery {
	query := (&QRCodeClient{config: frq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := frq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := frq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(filereference.Table, filereference.FieldID, selector),
			sqlgraph.To(qrcode.Table, qrcode.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, filereference.QrCodeTable, filereference.QrCodeColumn),
		)
		fromU = sqlgraph.SetNeighbors(frq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FileReference entity from the query.
// Returns a *NotFoundError when no FileReference was found.
func (frq *FileReferenceQuery) First(ctx context.Context) (*FileReference, error) {
	nodes, err := frq.Limit(1).All(setContextOp(ctx, frq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{filereference.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (frq *FileReferenceQuery) FirstX(ctx context.Context) *FileReference {
	node, err := frq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FileReference ID from the query.
// Returns a *NotFoundError when no FileReference ID was found.
func (frq *FileReferenceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = frq.Limit(1).IDs(setContextOp(ctx, frq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{filereference.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (frq *FileReferenceQuery) FirstIDX(ctx context.Context) int {
	id, err := frq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FileReference entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FileReference entity is found.
// Returns a *NotFoundError when no FileReference entities are found.
func (frq *FileReferenceQuery) Only(ctx context.Context) (*FileReference, error) {
	nodes, err := frq.Limit(2).All(setContextOp(ctx, frq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{filereference.Label}
	default:
		return nil, &NotSingularError{filereference.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (frq *FileReferenceQuery) OnlyX(ctx context.Context) *FileReference {
	node, err := frq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FileReference ID in the query.
// Returns a *NotSingularError when more than one FileReference ID is found.
// Returns a *NotFoundError when no entities are found.
func (frq *FileReferenceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = frq.Limit(2).IDs(setContextOp(ctx, frq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{filereference.Label}
	default:
		err = &NotSingularError{filereference.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (frq *FileReferenceQuery) OnlyIDX(ctx context.Context) int {
	id, err := frq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FileReferences.
func (frq *FileReferenceQuery) All(ctx context.Context) ([]*FileReference, error) {
	ctx = setContextOp(ctx, frq.ctx, ent.OpQueryAll)
	if err := frq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FileReference, *FileReferenceQuery]()
	return withInterceptors[[]*FileReference](ctx, frq, qr, frq.inters)
}

// AllX is like All, but panics if an error occurs.
func (frq *FileReferenceQuery) AllX(ctx context.Context) []*FileReference {
	nodes, err := frq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FileReference IDs.
func (frq *FileReferenceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if frq.ctx.Unique == nil && frq.path != nil {
		frq.Unique(true)
	}
	ctx = setContextOp(ctx, frq.ctx, ent.OpQueryIDs)
	if err = frq.Select(filereference.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (frq *FileReferenceQuery) IDsX(ctx context.Context) []int {
	ids, err := frq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (frq *FileReferenceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, frq.ctx, ent.OpQueryCount)
	if err := frq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, frq, querierCount[*FileReferenceQuery](), frq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (frq *FileReferenceQuery) CountX(ctx context.Context) int {
	count, err := frq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (frq *FileReferenceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, frq.ctx, ent.OpQueryExist)
	switch _, err := frq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (frq *FileReferenceQuery) ExistX(ctx context.Context) bool {
	exist, err := frq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FileReferenceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (frq *FileReferenceQuery) Clone() *FileReferenceQuery {
	if frq == nil {
		return nil
	}
	return &FileReferenceQuery{
		config:     frq.config,
		ctx:        frq.ctx.Clone(),
		order:      append([]filereference.OrderOption{}, frq.order...),
		inters:     append([]Interceptor{}, frq.inters...),
		predicates: append([]predicate.FileReference{}, frq.predicates...),
		withQrCode: frq.withQrCode.Clone(),
		// clone intermediate query.
		sql:  frq.sql.Clone(),
		path: frq.path,
	}
}

// WithQrCode tells the query-builder to eager-load the nodes that are connected to
// the "qr_code" edge. The optional arguments are used to configure the query builder of the edge.
func (frq *FileReferenceQuery) WithQrCode(opts ...func(*QRCodeQuery)) *FileReferenceQuery {
	query := (&QRCodeClient{config: frq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	frq.withQrCode = query
	return frq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Filename string `json:"filename,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FileReference.Query().
//		GroupBy(filereference.FieldFilename).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (frq *FileReferenceQuery) GroupBy(field string, fields ...string) *FileReferenceGroupBy {
	frq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FileReferenceGroupBy{build: frq}
	grbuild.flds = &frq.ctx.Fields
	grbuild.label = filereference.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Filename string `json:"filename,omitempty"`
//	}
//
//	client.FileReference.Query().
//		Select(filereference.FieldFilename).
//		Scan(ctx, &v)
func (frq *FileReferenceQuery) Select(fields ...string) *FileReferenceSelect {
	frq.ctx.Fields = append(frq.ctx.Fields, fields...)
	sbuild := &FileReferenceSelect{FileReferenceQuery: frq}
	sbuild.label = filereference.Label
	sbuild.flds, sbuild.scan = &frq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FileReferenceSelect configured with the given aggregations.
func (frq *FileReferenceQuery) Aggregate(fns ...AggregateFunc) *FileReferenceSelect {
	return frq.Select().Aggregate(fns...)
}

func (frq *FileReferenceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range frq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, frq); err != nil {
				return err
			}
		}
	}
	for _, f := range frq.ctx.Fields {
		if !filereference.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if frq.path != nil {
		prev, err := frq.path(ctx)
		if err != nil {
			return err
		}
		frq.sql = prev
	}
	return nil
}

func (frq *FileReferenceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FileReference, error) {
	var (
		nodes       = []*FileReference{}
		withFKs     = frq.withFKs
		_spec       = frq.querySpec()
		loadedTypes = [1]bool{
			frq.withQrCode != nil,
		}
	)
	if frq.withQrCode != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, filereference.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FileReference).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FileReference{config: frq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, frq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := frq.withQrCode; query != nil {
		if err := frq.loadQrCode(ctx, query, nodes, nil,
			func(n *FileReference, e *QRCode) { n.Edges.QrCode = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (frq *FileReferenceQuery) loadQrCode(ctx context.Context, query *QRCodeQuery, nodes []*FileReference, init func(*FileReference), assign func(*FileReference, *QRCode)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*FileReference)
	for i := range nodes {
		if nodes[i].qr_code_file_refs == nil {
			continue
		}
		fk := *nodes[i].qr_code_file_refs
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(qrcode.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "qr_code_file_refs" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (frq *FileReferenceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := frq.querySpec()
	_spec.Node.Columns = frq.ctx.Fields
	if len(frq.ctx.Fields) > 0 {
		_spec.Unique = frq.ctx.Unique != nil && *frq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, frq.driver, _spec)
}

func (frq *FileReferenceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(filereference.Table, filereference.Columns, sqlgraph.NewFieldSpec(filereference.FieldID, field.TypeInt))
	_spec.From = frq.sql
	if unique := frq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if frq.path != nil {
		_spec.Unique = true
	}
	if fields := frq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, filereference.FieldID)
		for i := range fields {
			if fields[i] != filereference.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := frq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := frq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := frq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := frq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (frq *FileReferenceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(frq.driver.Dialect())
	t1 := builder.Table(filereference.Table)
	columns := frq.ctx.Fields
	if len(columns) == 0 {
		columns = filereference.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if frq.sql != nil {
		selector = frq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if frq.ctx.Unique != nil && *frq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range frq.predicates {
		p(selector)
	}
	for _, p := range frq.order {
		p(selector)
	}
	if offset := frq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := frq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FileReferenceGroupBy is the group-by builder for FileReference entities.
type FileReferenceGroupBy struct {
	selector
	build *FileReferenceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (frgb *FileReferenceGroupBy) Aggregate(fns ...AggregateFunc) *FileReferenceGroupBy {
	frgb.fns = append(frgb.fns, fns...)
	return frgb
}

// Scan applies the selector query and scans the result into the given value.
func (frgb *FileReferenceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, frgb.build.ctx, ent.OpQueryGroupBy)
	if err := frgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FileReferenceQuery, *FileReferenceGroupBy](ctx, frgb.build, frgb, frgb.build.inters, v)
}

func (frgb *FileReferenceGroupBy) sqlScan(ctx context.Context, root *FileReferenceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(frgb.fns))
	for _, fn := range frgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*frgb.flds)+len(frgb.fns))
		for _, f := range *frgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*frgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := frgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FileReferenceSelect is the builder for selecting fields of FileReference entities.
type FileReferenceSelect struct {
	*FileReferenceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (frs *FileReferenceSelect) Aggregate(fns ...AggregateFunc) *FileReferenceSelect {
	frs.fns = append(frs.fns, fns...)
	return frs
}

// Scan applies the selector query and scans the result into the given value.
func (frs *FileReferenceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, frs.ctx, ent.OpQuerySelect)
	if err := frs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FileReferenceQuery, *FileReferenceSelect](ctx, frs.FileReferenceQuery, frs, frs.inters, v)
}

func (frs *FileReferenceSelect) sqlScan(ctx context.Context, root *FileReferenceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(frs.fns))
	for _, fn := range frs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*frs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := frs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
