// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"qr_backend/ent/predicate"
	"qr_backend/ent/qrcode"
	"qr_backend/ent/qrcodeanalytics"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QRCodeAnalyticsQuery is the builder for querying QRCodeAnalytics entities.
type QRCodeAnalyticsQuery struct {
	config
	ctx        *QueryContext
	order      []qrcodeanalytics.OrderOption
	inters     []Interceptor
	predicates []predicate.QRCodeAnalytics
	withQrCode *QRCodeQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the QRCodeAnalyticsQuery builder.
func (qcaq *QRCodeAnalyticsQuery) Where(ps ...predicate.QRCodeAnalytics) *QRCodeAnalyticsQuery {
	qcaq.predicates = append(qcaq.predicates, ps...)
	return qcaq
}

// Limit the number of records to be returned by this query.
func (qcaq *QRCodeAnalyticsQuery) Limit(limit int) *QRCodeAnalyticsQuery {
	qcaq.ctx.Limit = &limit
	return qcaq
}

// Offset to start from.
func (qcaq *QRCodeAnalyticsQuery) Offset(offset int) *QRCodeAnalyticsQuery {
	qcaq.ctx.Offset = &offset
	return qcaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (qcaq *QRCodeAnalyticsQuery) Unique(unique bool) *QRCodeAnalyticsQuery {
	qcaq.ctx.Unique = &unique
	return qcaq
}

// Order specifies how the records should be ordered.
func (qcaq *QRCodeAnalyticsQuery) Order(o ...qrcodeanalytics.OrderOption) *QRCodeAnalyticsQuery {
	qcaq.order = append(qcaq.order, o...)
	return qcaq
}

// QueryQrCode chains the current query on the "qr_code" edge.
func (qcaq *QRCodeAnalyticsQuery) QueryQrCode() *QRCodeQuery {
	query := (&QRCodeClient{config: qcaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := qcaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := qcaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(qrcodeanalytics.Table, qrcodeanalytics.FieldID, selector),
			sqlgraph.To(qrcode.Table, qrcode.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, qrcodeanalytics.QrCodeTable, qrcodeanalytics.QrCodeColumn),
		)
		fromU = sqlgraph.SetNeighbors(qcaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first QRCodeAnalytics entity from the query.
// Returns a *NotFoundError when no QRCodeAnalytics was found.
func (qcaq *QRCodeAnalyticsQuery) First(ctx context.Context) (*QRCodeAnalytics, error) {
	nodes, err := qcaq.Limit(1).All(setContextOp(ctx, qcaq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{qrcodeanalytics.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (qcaq *QRCodeAnalyticsQuery) FirstX(ctx context.Context) *QRCodeAnalytics {
	node, err := qcaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first QRCodeAnalytics ID from the query.
// Returns a *NotFoundError when no QRCodeAnalytics ID was found.
func (qcaq *QRCodeAnalyticsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = qcaq.Limit(1).IDs(setContextOp(ctx, qcaq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{qrcodeanalytics.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (qcaq *QRCodeAnalyticsQuery) FirstIDX(ctx context.Context) int {
	id, err := qcaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single QRCodeAnalytics entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one QRCodeAnalytics entity is found.
// Returns a *NotFoundError when no QRCodeAnalytics entities are found.
func (qcaq *QRCodeAnalyticsQuery) Only(ctx context.Context) (*QRCodeAnalytics, error) {
	nodes, err := qcaq.Limit(2).All(setContextOp(ctx, qcaq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{qrcodeanalytics.Label}
	default:
		return nil, &NotSingularError{qrcodeanalytics.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (qcaq *QRCodeAnalyticsQuery) OnlyX(ctx context.Context) *QRCodeAnalytics {
	node, err := qcaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only QRCodeAnalytics ID in the query.
// Returns a *NotSingularError when more than one QRCodeAnalytics ID is found.
// Returns a *NotFoundError when no entities are found.
func (qcaq *QRCodeAnalyticsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = qcaq.Limit(2).IDs(setContextOp(ctx, qcaq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{qrcodeanalytics.Label}
	default:
		err = &NotSingularError{qrcodeanalytics.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (qcaq *QRCodeAnalyticsQuery) OnlyIDX(ctx context.Context) int {
	id, err := qcaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of QRCodeAnalyticsSlice.
func (qcaq *QRCodeAnalyticsQuery) All(ctx context.Context) ([]*QRCodeAnalytics, error) {
	ctx = setContextOp(ctx, qcaq.ctx, ent.OpQueryAll)
	if err := qcaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*QRCodeAnalytics, *QRCodeAnalyticsQuery]()
	return withInterceptors[[]*QRCodeAnalytics](ctx, qcaq, qr, qcaq.inters)
}

// AllX is like All, but panics if an error occurs.
func (qcaq *QRCodeAnalyticsQuery) AllX(ctx context.Context) []*QRCodeAnalytics {
	nodes, err := qcaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of QRCodeAnalytics IDs.
func (qcaq *QRCodeAnalyticsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if qcaq.ctx.Unique == nil && qcaq.path != nil {
		qcaq.Unique(true)
	}
	ctx = setContextOp(ctx, qcaq.ctx, ent.OpQueryIDs)
	if err = qcaq.Select(qrcodeanalytics.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (qcaq *QRCodeAnalyticsQuery) IDsX(ctx context.Context) []int {
	ids, err := qcaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (qcaq *QRCodeAnalyticsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, qcaq.ctx, ent.OpQueryCount)
	if err := qcaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, qcaq, querierCount[*QRCodeAnalyticsQuery](), qcaq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (qcaq *QRCodeAnalyticsQuery) CountX(ctx context.Context) int {
	count, err := qcaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (qcaq *QRCodeAnalyticsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, qcaq.ctx, ent.OpQueryExist)
	switch _, err := qcaq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (qcaq *QRCodeAnalyticsQuery) ExistX(ctx context.Context) bool {
	exist, err := qcaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the QRCodeAnalyticsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (qcaq *QRCodeAnalyticsQuery) Clone() *QRCodeAnalyticsQuery {
	if qcaq == nil {
		return nil
	}
	return &QRCodeAnalyticsQuery{
		config:     qcaq.config,
		ctx:        qcaq.ctx.Clone(),
		order:      append([]qrcodeanalytics.OrderOption{}, qcaq.order...),
		inters:     append([]Interceptor{}, qcaq.inters...),
		predicates: append([]predicate.QRCodeAnalytics{}, qcaq.predicates...),
		withQrCode: qcaq.withQrCode.Clone(),
		// clone intermediate query.
		sql:  qcaq.sql.Clone(),
		path: qcaq.path,
	}
}

// WithQrCode tells the query-builder to eager-load the nodes that are connected to
// the "qr_code" edge. The optional arguments are used to configure the query builder of the edge.
func (qcaq *QRCodeAnalyticsQuery) WithQrCode(opts ...func(*QRCodeQuery)) *QRCodeAnalyticsQuery {
	query := (&QRCodeClient{config: qcaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	qcaq.withQrCode = query
	return qcaq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		IPAddress string `json:"ip_address,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.QRCodeAnalytics.Query().
//		GroupBy(qrcodeanalytics.FieldIPAddress).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (qcaq *QRCodeAnalyticsQuery) GroupBy(field string, fields ...string) *QRCodeAnalyticsGroupBy {
	qcaq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &QRCodeAnalyticsGroupBy{build: qcaq}
	grbuild.flds = &qcaq.ctx.Fields
	grbuild.label = qrcodeanalytics.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		IPAddress string `json:"ip_address,omitempty"`
//	}
//
//	client.QRCodeAnalytics.Query().
//		Select(qrcodeanalytics.FieldIPAddress).
//		Scan(ctx, &v)
func (qcaq *QRCodeAnalyticsQuery) Select(fields ...string) *QRCodeAnalyticsSelect {
	qcaq.ctx.Fields = append(qcaq.ctx.Fields, fields...)
	sbuild := &QRCodeAnalyticsSelect{QRCodeAnalyticsQuery: qcaq}
	sbuild.label = qrcodeanalytics.Label
	sbuild.flds, sbuild.scan = &qcaq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a QRCodeAnalyticsSelect configured with the given aggregations.
func (qcaq *QRCodeAnalyticsQuery) Aggregate(fns ...AggregateFunc) *QRCodeAnalyticsSelect {
	return qcaq.Select().Aggregate(fns...)
}

func (qcaq *QRCodeAnalyticsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range qcaq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, qcaq); err != nil {
				return err
			}
		}
	}
	for _, f := range qcaq.ctx.Fields {
		if !qrcodeanalytics.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if qcaq.path != nil {
		prev, err := qcaq.path(ctx)
		if err != nil {
			return err
		}
		qcaq.sql = prev
	}
	return nil
}

func (qcaq *QRCodeAnalyticsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*QRCodeAnalytics, error) {
	var (
		nodes       = []*QRCodeAnalytics{}
		withFKs     = qcaq.withFKs
		_spec       = qcaq.querySpec()
		loadedTypes = [1]bool{
			qcaq.withQrCode != nil,
		}
	)
	if qcaq.withQrCode != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, qrcodeanalytics.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*QRCodeAnalytics).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &QRCodeAnalytics{config: qcaq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, qcaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := qcaq.withQrCode; query != nil {
		if err := qcaq.loadQrCode(ctx, query, nodes, nil,
			func(n *QRCodeAnalytics, e *QRCode) { n.Edges.QrCode = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (qcaq *QRCodeAnalyticsQuery) loadQrCode(ctx context.Context, query *QRCodeQuery, nodes []*QRCodeAnalytics, init func(*QRCodeAnalytics), assign func(*QRCodeAnalytics, *QRCode)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*QRCodeAnalytics)
	for i := range nodes {
		if nodes[i].qr_code_analytics_records == nil {
			continue
		}
		fk := *nodes[i].qr_code_analytics_records
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(qrcode.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "qr_code_analytics_records" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (qcaq *QRCodeAnalyticsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := qcaq.querySpec()
	_spec.Node.Columns = qcaq.ctx.Fields
	if len(qcaq.ctx.Fields) > 0 {
		_spec.Unique = qcaq.ctx.Unique != nil && *qcaq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, qcaq.driver, _spec)
}

func (qcaq *QRCodeAnalyticsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(qrcodeanalytics.Table, qrcodeanalytics.Columns, sqlgraph.NewFieldSpec(qrcodeanalytics.FieldID, field.TypeInt))
	_spec.From = qcaq.sql
	if unique := qcaq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if qcaq.path != nil {
		_spec.Unique = true
	}
	if fields := qcaq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, qrcodeanalytics.FieldID)
		for i := range fields {
			if fields[i] != qrcodeanalytics.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := qcaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := qcaq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := qcaq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := qcaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (qcaq *QRCodeAnalyticsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(qcaq.driver.Dialect())
	t1 := builder.Table(qrcodeanalytics.Table)
	columns := qcaq.ctx.Fields
	if len(columns) == 0 {
		columns = qrcodeanalytics.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if qcaq.sql != nil {
		selector = qcaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if qcaq.ctx.Unique != nil && *qcaq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range qcaq.predicates {
		p(selector)
	}
	for _, p := range qcaq.order {
		p(selector)
	}
	if offset := qcaq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := qcaq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// QRCodeAnalyticsGroupBy is the group-by builder for QRCodeAnalytics entities.
type QRCodeAnalyticsGroupBy struct {
	selector
	build *QRCodeAnalyticsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (qcagb *QRCodeAnalyticsGroupBy) Aggregate(fns ...AggregateFunc) *QRCodeAnalyticsGroupBy {
	qcagb.fns = append(qcagb.fns, fns...)
	return qcagb
}

// Scan applies the selector query and scans the result into the given value.
func (qcagb *QRCodeAnalyticsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, qcagb.build.ctx, ent.OpQueryGroupBy)
	if err := qcagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QRCodeAnalyticsQuery, *QRCodeAnalyticsGroupBy](ctx, qcagb.build, qcagb, qcagb.build.inters, v)
}

func (qcagb *QRCodeAnalyticsGroupBy) sqlScan(ctx context.Context, root *QRCodeAnalyticsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(qcagb.fns))
	for _, fn := range qcagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*qcagb.flds)+len(qcagb.fns))
		for _, f := range *qcagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*qcagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qcagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// QRCodeAnalyticsSelect is the builder for selecting fields of QRCodeAnalytics entities.
type QRCodeAnalyticsSelect struct {
	*QRCodeAnalyticsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (qcas *QRCodeAnalyticsSelect) Aggregate(fns ...AggregateFunc) *QRCodeAnalyticsSelect {
	qcas.fns = append(qcas.fns, fns...)
	return qcas
}

// Scan applies the selector query and scans the result into the given value.
func (qcas *QRCodeAnalyticsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, qcas.ctx, ent.OpQuerySelect)
	if err := qcas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QRCodeAnalyticsQuery, *QRCodeAnalyticsSelect](ctx, qcas.QRCodeAnalyticsQuery, qcas, qcas.inters, v)
}

func (qcas *QRCodeAnalyticsSelect) sqlScan(ctx context.Context, root *QRCodeAnalyticsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(qcas.fns))
	for _, fn := range qcas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*qcas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qcas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
