// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"qr_backend/ent/qrcode"
	"qr_backend/ent/qrcodegroup"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QRCodeGroupCreate is the builder for creating a QRCodeGroup entity.
type QRCodeGroupCreate struct {
	config
	mutation *QRCodeGroupMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (qcgc *QRCodeGroupCreate) SetName(s string) *QRCodeGroupCreate {
	qcgc.mutation.SetName(s)
	return qcgc
}

// SetDescription sets the "description" field.
func (qcgc *QRCodeGroupCreate) SetDescription(s string) *QRCodeGroupCreate {
	qcgc.mutation.SetDescription(s)
	return qcgc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (qcgc *QRCodeGroupCreate) SetNillableDescription(s *string) *QRCodeGroupCreate {
	if s != nil {
		qcgc.SetDescription(*s)
	}
	return qcgc
}

// SetCreatedAt sets the "created_at" field.
func (qcgc *QRCodeGroupCreate) SetCreatedAt(t time.Time) *QRCodeGroupCreate {
	qcgc.mutation.SetCreatedAt(t)
	return qcgc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (qcgc *QRCodeGroupCreate) SetNillableCreatedAt(t *time.Time) *QRCodeGroupCreate {
	if t != nil {
		qcgc.SetCreatedAt(*t)
	}
	return qcgc
}

// SetUpdatedAt sets the "updated_at" field.
func (qcgc *QRCodeGroupCreate) SetUpdatedAt(t time.Time) *QRCodeGroupCreate {
	qcgc.mutation.SetUpdatedAt(t)
	return qcgc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (qcgc *QRCodeGroupCreate) SetNillableUpdatedAt(t *time.Time) *QRCodeGroupCreate {
	if t != nil {
		qcgc.SetUpdatedAt(*t)
	}
	return qcgc
}

// AddQrcodeIDs adds the "qrcodes" edge to the QRCode entity by IDs.
func (qcgc *QRCodeGroupCreate) AddQrcodeIDs(ids ...int) *QRCodeGroupCreate {
	qcgc.mutation.AddQrcodeIDs(ids...)
	return qcgc
}

// AddQrcodes adds the "qrcodes" edges to the QRCode entity.
func (qcgc *QRCodeGroupCreate) AddQrcodes(q ...*QRCode) *QRCodeGroupCreate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return qcgc.AddQrcodeIDs(ids...)
}

// Mutation returns the QRCodeGroupMutation object of the builder.
func (qcgc *QRCodeGroupCreate) Mutation() *QRCodeGroupMutation {
	return qcgc.mutation
}

// Save creates the QRCodeGroup in the database.
func (qcgc *QRCodeGroupCreate) Save(ctx context.Context) (*QRCodeGroup, error) {
	qcgc.defaults()
	return withHooks(ctx, qcgc.sqlSave, qcgc.mutation, qcgc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (qcgc *QRCodeGroupCreate) SaveX(ctx context.Context) *QRCodeGroup {
	v, err := qcgc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qcgc *QRCodeGroupCreate) Exec(ctx context.Context) error {
	_, err := qcgc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qcgc *QRCodeGroupCreate) ExecX(ctx context.Context) {
	if err := qcgc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (qcgc *QRCodeGroupCreate) defaults() {
	if _, ok := qcgc.mutation.CreatedAt(); !ok {
		v := qrcodegroup.DefaultCreatedAt()
		qcgc.mutation.SetCreatedAt(v)
	}
	if _, ok := qcgc.mutation.UpdatedAt(); !ok {
		v := qrcodegroup.DefaultUpdatedAt()
		qcgc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (qcgc *QRCodeGroupCreate) check() error {
	if _, ok := qcgc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "QRCodeGroup.name"`)}
	}
	if v, ok := qcgc.mutation.Name(); ok {
		if err := qrcodegroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "QRCodeGroup.name": %w`, err)}
		}
	}
	if _, ok := qcgc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "QRCodeGroup.created_at"`)}
	}
	if _, ok := qcgc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "QRCodeGroup.updated_at"`)}
	}
	return nil
}

func (qcgc *QRCodeGroupCreate) sqlSave(ctx context.Context) (*QRCodeGroup, error) {
	if err := qcgc.check(); err != nil {
		return nil, err
	}
	_node, _spec := qcgc.createSpec()
	if err := sqlgraph.CreateNode(ctx, qcgc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	qcgc.mutation.id = &_node.ID
	qcgc.mutation.done = true
	return _node, nil
}

func (qcgc *QRCodeGroupCreate) createSpec() (*QRCodeGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &QRCodeGroup{config: qcgc.config}
		_spec = sqlgraph.NewCreateSpec(qrcodegroup.Table, sqlgraph.NewFieldSpec(qrcodegroup.FieldID, field.TypeInt))
	)
	if value, ok := qcgc.mutation.Name(); ok {
		_spec.SetField(qrcodegroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := qcgc.mutation.Description(); ok {
		_spec.SetField(qrcodegroup.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := qcgc.mutation.CreatedAt(); ok {
		_spec.SetField(qrcodegroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := qcgc.mutation.UpdatedAt(); ok {
		_spec.SetField(qrcodegroup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := qcgc.mutation.QrcodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   qrcodegroup.QrcodesTable,
			Columns: []string{qrcodegroup.QrcodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(qrcode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// QRCodeGroupCreateBulk is the builder for creating many QRCodeGroup entities in bulk.
type QRCodeGroupCreateBulk struct {
	config
	err      error
	builders []*QRCodeGroupCreate
}

// Save creates the QRCodeGroup entities in the database.
func (qcgcb *QRCodeGroupCreateBulk) Save(ctx context.Context) ([]*QRCodeGroup, error) {
	if qcgcb.err != nil {
		return nil, qcgcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(qcgcb.builders))
	nodes := make([]*QRCodeGroup, len(qcgcb.builders))
	mutators := make([]Mutator, len(qcgcb.builders))
	for i := range qcgcb.builders {
		func(i int, root context.Context) {
			builder := qcgcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QRCodeGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, qcgcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, qcgcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, qcgcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (qcgcb *QRCodeGroupCreateBulk) SaveX(ctx context.Context) []*QRCodeGroup {
	v, err := qcgcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qcgcb *QRCodeGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := qcgcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qcgcb *QRCodeGroupCreateBulk) ExecX(ctx context.Context) {
	if err := qcgcb.Exec(ctx); err != nil {
		panic(err)
	}
}
