// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"qr_backend/ent/qrcodegroup"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// QRCodeGroup is the model entity for the QRCodeGroup schema.
type QRCodeGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the QRCodeGroupQuery when eager-loading is set.
	Edges        QRCodeGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// QRCodeGroupEdges holds the relations/edges for other nodes in the graph.
type QRCodeGroupEdges struct {
	// Qrcodes holds the value of the qrcodes edge.
	Qrcodes []*QRCode `json:"qrcodes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// QrcodesOrErr returns the Qrcodes value or an error if the edge
// was not loaded in eager-loading.
func (e QRCodeGroupEdges) QrcodesOrErr() ([]*QRCode, error) {
	if e.loadedTypes[0] {
		return e.Qrcodes, nil
	}
	return nil, &NotLoadedError{edge: "qrcodes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*QRCodeGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case qrcodegroup.FieldID:
			values[i] = new(sql.NullInt64)
		case qrcodegroup.FieldName, qrcodegroup.FieldDescription:
			values[i] = new(sql.NullString)
		case qrcodegroup.FieldCreatedAt, qrcodegroup.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the QRCodeGroup fields.
func (qcg *QRCodeGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case qrcodegroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			qcg.ID = int(value.Int64)
		case qrcodegroup.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				qcg.Name = value.String
			}
		case qrcodegroup.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				qcg.Description = value.String
			}
		case qrcodegroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				qcg.CreatedAt = value.Time
			}
		case qrcodegroup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				qcg.UpdatedAt = value.Time
			}
		default:
			qcg.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the QRCodeGroup.
// This includes values selected through modifiers, order, etc.
func (qcg *QRCodeGroup) Value(name string) (ent.Value, error) {
	return qcg.selectValues.Get(name)
}

// QueryQrcodes queries the "qrcodes" edge of the QRCodeGroup entity.
func (qcg *QRCodeGroup) QueryQrcodes() *QRCodeQuery {
	return NewQRCodeGroupClient(qcg.config).QueryQrcodes(qcg)
}

// Update returns a builder for updating this QRCodeGroup.
// Note that you need to call QRCodeGroup.Unwrap() before calling this method if this QRCodeGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (qcg *QRCodeGroup) Update() *QRCodeGroupUpdateOne {
	return NewQRCodeGroupClient(qcg.config).UpdateOne(qcg)
}

// Unwrap unwraps the QRCodeGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (qcg *QRCodeGroup) Unwrap() *QRCodeGroup {
	_tx, ok := qcg.config.driver.(*txDriver)
	if !ok {
		panic("ent: QRCodeGroup is not a transactional entity")
	}
	qcg.config.driver = _tx.drv
	return qcg
}

// String implements the fmt.Stringer.
func (qcg *QRCodeGroup) String() string {
	var builder strings.Builder
	builder.WriteString("QRCodeGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", qcg.ID))
	builder.WriteString("name=")
	builder.WriteString(qcg.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(qcg.Description)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(qcg.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(qcg.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// QRCodeGroups is a parsable slice of QRCodeGroup.
type QRCodeGroups []*QRCodeGroup
