// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"qr_backend/ent/filereference"
	"qr_backend/ent/predicate"
	"qr_backend/ent/qrcode"
	"qr_backend/ent/qrcodeanalytics"
	"qr_backend/ent/qrcodegroup"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QRCodeQuery is the builder for querying QRCode entities.
type QRCodeQuery struct {
	config
	ctx                  *QueryContext
	order                []qrcode.OrderOption
	inters               []Interceptor
	predicates           []predicate.QRCode
	withFileRefs         *FileReferenceQuery
	withGroup            *QRCodeGroupQuery
	withAnalyticsRecords *QRCodeAnalyticsQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the QRCodeQuery builder.
func (qcq *QRCodeQuery) Where(ps ...predicate.QRCode) *QRCodeQuery {
	qcq.predicates = append(qcq.predicates, ps...)
	return qcq
}

// Limit the number of records to be returned by this query.
func (qcq *QRCodeQuery) Limit(limit int) *QRCodeQuery {
	qcq.ctx.Limit = &limit
	return qcq
}

// Offset to start from.
func (qcq *QRCodeQuery) Offset(offset int) *QRCodeQuery {
	qcq.ctx.Offset = &offset
	return qcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (qcq *QRCodeQuery) Unique(unique bool) *QRCodeQuery {
	qcq.ctx.Unique = &unique
	return qcq
}

// Order specifies how the records should be ordered.
func (qcq *QRCodeQuery) Order(o ...qrcode.OrderOption) *QRCodeQuery {
	qcq.order = append(qcq.order, o...)
	return qcq
}

// QueryFileRefs chains the current query on the "file_refs" edge.
func (qcq *QRCodeQuery) QueryFileRefs() *FileReferenceQuery {
	query := (&FileReferenceClient{config: qcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := qcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := qcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(qrcode.Table, qrcode.FieldID, selector),
			sqlgraph.To(filereference.Table, filereference.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, qrcode.FileRefsTable, qrcode.FileRefsColumn),
		)
		fromU = sqlgraph.SetNeighbors(qcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroup chains the current query on the "group" edge.
func (qcq *QRCodeQuery) QueryGroup() *QRCodeGroupQuery {
	query := (&QRCodeGroupClient{config: qcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := qcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := qcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(qrcode.Table, qrcode.FieldID, selector),
			sqlgraph.To(qrcodegroup.Table, qrcodegroup.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, qrcode.GroupTable, qrcode.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(qcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAnalyticsRecords chains the current query on the "analytics_records" edge.
func (qcq *QRCodeQuery) QueryAnalyticsRecords() *QRCodeAnalyticsQuery {
	query := (&QRCodeAnalyticsClient{config: qcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := qcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := qcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(qrcode.Table, qrcode.FieldID, selector),
			sqlgraph.To(qrcodeanalytics.Table, qrcodeanalytics.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, qrcode.AnalyticsRecordsTable, qrcode.AnalyticsRecordsColumn),
		)
		fromU = sqlgraph.SetNeighbors(qcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first QRCode entity from the query.
// Returns a *NotFoundError when no QRCode was found.
func (qcq *QRCodeQuery) First(ctx context.Context) (*QRCode, error) {
	nodes, err := qcq.Limit(1).All(setContextOp(ctx, qcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{qrcode.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (qcq *QRCodeQuery) FirstX(ctx context.Context) *QRCode {
	node, err := qcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first QRCode ID from the query.
// Returns a *NotFoundError when no QRCode ID was found.
func (qcq *QRCodeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = qcq.Limit(1).IDs(setContextOp(ctx, qcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{qrcode.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (qcq *QRCodeQuery) FirstIDX(ctx context.Context) int {
	id, err := qcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single QRCode entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one QRCode entity is found.
// Returns a *NotFoundError when no QRCode entities are found.
func (qcq *QRCodeQuery) Only(ctx context.Context) (*QRCode, error) {
	nodes, err := qcq.Limit(2).All(setContextOp(ctx, qcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{qrcode.Label}
	default:
		return nil, &NotSingularError{qrcode.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (qcq *QRCodeQuery) OnlyX(ctx context.Context) *QRCode {
	node, err := qcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only QRCode ID in the query.
// Returns a *NotSingularError when more than one QRCode ID is found.
// Returns a *NotFoundError when no entities are found.
func (qcq *QRCodeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = qcq.Limit(2).IDs(setContextOp(ctx, qcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{qrcode.Label}
	default:
		err = &NotSingularError{qrcode.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (qcq *QRCodeQuery) OnlyIDX(ctx context.Context) int {
	id, err := qcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of QRCodes.
func (qcq *QRCodeQuery) All(ctx context.Context) ([]*QRCode, error) {
	ctx = setContextOp(ctx, qcq.ctx, ent.OpQueryAll)
	if err := qcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*QRCode, *QRCodeQuery]()
	return withInterceptors[[]*QRCode](ctx, qcq, qr, qcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (qcq *QRCodeQuery) AllX(ctx context.Context) []*QRCode {
	nodes, err := qcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of QRCode IDs.
func (qcq *QRCodeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if qcq.ctx.Unique == nil && qcq.path != nil {
		qcq.Unique(true)
	}
	ctx = setContextOp(ctx, qcq.ctx, ent.OpQueryIDs)
	if err = qcq.Select(qrcode.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (qcq *QRCodeQuery) IDsX(ctx context.Context) []int {
	ids, err := qcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (qcq *QRCodeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, qcq.ctx, ent.OpQueryCount)
	if err := qcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, qcq, querierCount[*QRCodeQuery](), qcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (qcq *QRCodeQuery) CountX(ctx context.Context) int {
	count, err := qcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (qcq *QRCodeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, qcq.ctx, ent.OpQueryExist)
	switch _, err := qcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (qcq *QRCodeQuery) ExistX(ctx context.Context) bool {
	exist, err := qcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the QRCodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (qcq *QRCodeQuery) Clone() *QRCodeQuery {
	if qcq == nil {
		return nil
	}
	return &QRCodeQuery{
		config:               qcq.config,
		ctx:                  qcq.ctx.Clone(),
		order:                append([]qrcode.OrderOption{}, qcq.order...),
		inters:               append([]Interceptor{}, qcq.inters...),
		predicates:           append([]predicate.QRCode{}, qcq.predicates...),
		withFileRefs:         qcq.withFileRefs.Clone(),
		withGroup:            qcq.withGroup.Clone(),
		withAnalyticsRecords: qcq.withAnalyticsRecords.Clone(),
		// clone intermediate query.
		sql:  qcq.sql.Clone(),
		path: qcq.path,
	}
}

// WithFileRefs tells the query-builder to eager-load the nodes that are connected to
// the "file_refs" edge. The optional arguments are used to configure the query builder of the edge.
func (qcq *QRCodeQuery) WithFileRefs(opts ...func(*FileReferenceQuery)) *QRCodeQuery {
	query := (&FileReferenceClient{config: qcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	qcq.withFileRefs = query
	return qcq
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (qcq *QRCodeQuery) WithGroup(opts ...func(*QRCodeGroupQuery)) *QRCodeQuery {
	query := (&QRCodeGroupClient{config: qcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	qcq.withGroup = query
	return qcq
}

// WithAnalyticsRecords tells the query-builder to eager-load the nodes that are connected to
// the "analytics_records" edge. The optional arguments are used to configure the query builder of the edge.
func (qcq *QRCodeQuery) WithAnalyticsRecords(opts ...func(*QRCodeAnalyticsQuery)) *QRCodeQuery {
	query := (&QRCodeAnalyticsClient{config: qcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	qcq.withAnalyticsRecords = query
	return qcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.QRCode.Query().
//		GroupBy(qrcode.FieldType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (qcq *QRCodeQuery) GroupBy(field string, fields ...string) *QRCodeGroupBy {
	qcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &QRCodeGroupBy{build: qcq}
	grbuild.flds = &qcq.ctx.Fields
	grbuild.label = qrcode.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//	}
//
//	client.QRCode.Query().
//		Select(qrcode.FieldType).
//		Scan(ctx, &v)
func (qcq *QRCodeQuery) Select(fields ...string) *QRCodeSelect {
	qcq.ctx.Fields = append(qcq.ctx.Fields, fields...)
	sbuild := &QRCodeSelect{QRCodeQuery: qcq}
	sbuild.label = qrcode.Label
	sbuild.flds, sbuild.scan = &qcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a QRCodeSelect configured with the given aggregations.
func (qcq *QRCodeQuery) Aggregate(fns ...AggregateFunc) *QRCodeSelect {
	return qcq.Select().Aggregate(fns...)
}

func (qcq *QRCodeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range qcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, qcq); err != nil {
				return err
			}
		}
	}
	for _, f := range qcq.ctx.Fields {
		if !qrcode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if qcq.path != nil {
		prev, err := qcq.path(ctx)
		if err != nil {
			return err
		}
		qcq.sql = prev
	}
	return nil
}

func (qcq *QRCodeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*QRCode, error) {
	var (
		nodes       = []*QRCode{}
		_spec       = qcq.querySpec()
		loadedTypes = [3]bool{
			qcq.withFileRefs != nil,
			qcq.withGroup != nil,
			qcq.withAnalyticsRecords != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*QRCode).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &QRCode{config: qcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, qcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := qcq.withFileRefs; query != nil {
		if err := qcq.loadFileRefs(ctx, query, nodes,
			func(n *QRCode) { n.Edges.FileRefs = []*FileReference{} },
			func(n *QRCode, e *FileReference) { n.Edges.FileRefs = append(n.Edges.FileRefs, e) }); err != nil {
			return nil, err
		}
	}
	if query := qcq.withGroup; query != nil {
		if err := qcq.loadGroup(ctx, query, nodes, nil,
			func(n *QRCode, e *QRCodeGroup) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	if query := qcq.withAnalyticsRecords; query != nil {
		if err := qcq.loadAnalyticsRecords(ctx, query, nodes,
			func(n *QRCode) { n.Edges.AnalyticsRecords = []*QRCodeAnalytics{} },
			func(n *QRCode, e *QRCodeAnalytics) { n.Edges.AnalyticsRecords = append(n.Edges.AnalyticsRecords, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (qcq *QRCodeQuery) loadFileRefs(ctx context.Context, query *FileReferenceQuery, nodes []*QRCode, init func(*QRCode), assign func(*QRCode, *FileReference)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*QRCode)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.FileReference(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(qrcode.FileRefsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.qr_code_file_refs
		if fk == nil {
			return fmt.Errorf(`foreign-key "qr_code_file_refs" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "qr_code_file_refs" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (qcq *QRCodeQuery) loadGroup(ctx context.Context, query *QRCodeGroupQuery, nodes []*QRCode, init func(*QRCode), assign func(*QRCode, *QRCodeGroup)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*QRCode)
	for i := range nodes {
		if nodes[i].GroupID == nil {
			continue
		}
		fk := *nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(qrcodegroup.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (qcq *QRCodeQuery) loadAnalyticsRecords(ctx context.Context, query *QRCodeAnalyticsQuery, nodes []*QRCode, init func(*QRCode), assign func(*QRCode, *QRCodeAnalytics)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*QRCode)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.QRCodeAnalytics(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(qrcode.AnalyticsRecordsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.qr_code_analytics_records
		if fk == nil {
			return fmt.Errorf(`foreign-key "qr_code_analytics_records" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "qr_code_analytics_records" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (qcq *QRCodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := qcq.querySpec()
	_spec.Node.Columns = qcq.ctx.Fields
	if len(qcq.ctx.Fields) > 0 {
		_spec.Unique = qcq.ctx.Unique != nil && *qcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, qcq.driver, _spec)
}

func (qcq *QRCodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(qrcode.Table, qrcode.Columns, sqlgraph.NewFieldSpec(qrcode.FieldID, field.TypeInt))
	_spec.From = qcq.sql
	if unique := qcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if qcq.path != nil {
		_spec.Unique = true
	}
	if fields := qcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, qrcode.FieldID)
		for i := range fields {
			if fields[i] != qrcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if qcq.withGroup != nil {
			_spec.Node.AddColumnOnce(qrcode.FieldGroupID)
		}
	}
	if ps := qcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := qcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := qcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := qcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (qcq *QRCodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(qcq.driver.Dialect())
	t1 := builder.Table(qrcode.Table)
	columns := qcq.ctx.Fields
	if len(columns) == 0 {
		columns = qrcode.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if qcq.sql != nil {
		selector = qcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if qcq.ctx.Unique != nil && *qcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range qcq.predicates {
		p(selector)
	}
	for _, p := range qcq.order {
		p(selector)
	}
	if offset := qcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := qcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// QRCodeGroupBy is the group-by builder for QRCode entities.
type QRCodeGroupBy struct {
	selector
	build *QRCodeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (qcgb *QRCodeGroupBy) Aggregate(fns ...AggregateFunc) *QRCodeGroupBy {
	qcgb.fns = append(qcgb.fns, fns...)
	return qcgb
}

// Scan applies the selector query and scans the result into the given value.
func (qcgb *QRCodeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, qcgb.build.ctx, ent.OpQueryGroupBy)
	if err := qcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QRCodeQuery, *QRCodeGroupBy](ctx, qcgb.build, qcgb, qcgb.build.inters, v)
}

func (qcgb *QRCodeGroupBy) sqlScan(ctx context.Context, root *QRCodeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(qcgb.fns))
	for _, fn := range qcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*qcgb.flds)+len(qcgb.fns))
		for _, f := range *qcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*qcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// QRCodeSelect is the builder for selecting fields of QRCode entities.
type QRCodeSelect struct {
	*QRCodeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (qcs *QRCodeSelect) Aggregate(fns ...AggregateFunc) *QRCodeSelect {
	qcs.fns = append(qcs.fns, fns...)
	return qcs
}

// Scan applies the selector query and scans the result into the given value.
func (qcs *QRCodeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, qcs.ctx, ent.OpQuerySelect)
	if err := qcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QRCodeQuery, *QRCodeSelect](ctx, qcs.QRCodeQuery, qcs, qcs.inters, v)
}

func (qcs *QRCodeSelect) sqlScan(ctx context.Context, root *QRCodeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(qcs.fns))
	for _, fn := range qcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*qcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
