// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"qr_backend/ent/predicate"
	"qr_backend/ent/qrcodeanalytics"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QRCodeAnalyticsDelete is the builder for deleting a QRCodeAnalytics entity.
type QRCodeAnalyticsDelete struct {
	config
	hooks    []Hook
	mutation *QRCodeAnalyticsMutation
}

// Where appends a list predicates to the QRCodeAnalyticsDelete builder.
func (qcad *QRCodeAnalyticsDelete) Where(ps ...predicate.QRCodeAnalytics) *QRCodeAnalyticsDelete {
	qcad.mutation.Where(ps...)
	return qcad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (qcad *QRCodeAnalyticsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, qcad.sqlExec, qcad.mutation, qcad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (qcad *QRCodeAnalyticsDelete) ExecX(ctx context.Context) int {
	n, err := qcad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (qcad *QRCodeAnalyticsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(qrcodeanalytics.Table, sqlgraph.NewFieldSpec(qrcodeanalytics.FieldID, field.TypeInt))
	if ps := qcad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, qcad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	qcad.mutation.done = true
	return affected, err
}

// QRCodeAnalyticsDeleteOne is the builder for deleting a single QRCodeAnalytics entity.
type QRCodeAnalyticsDeleteOne struct {
	qcad *QRCodeAnalyticsDelete
}

// Where appends a list predicates to the QRCodeAnalyticsDelete builder.
func (qcado *QRCodeAnalyticsDeleteOne) Where(ps ...predicate.QRCodeAnalytics) *QRCodeAnalyticsDeleteOne {
	qcado.qcad.mutation.Where(ps...)
	return qcado
}

// Exec executes the deletion query.
func (qcado *QRCodeAnalyticsDeleteOne) Exec(ctx context.Context) error {
	n, err := qcado.qcad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{qrcodeanalytics.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (qcado *QRCodeAnalyticsDeleteOne) ExecX(ctx context.Context) {
	if err := qcado.Exec(ctx); err != nil {
		panic(err)
	}
}
