// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"qr_backend/ent/predicate"
	"qr_backend/ent/qrcode"
	"qr_backend/ent/qrcodegroup"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QRCodeGroupQuery is the builder for querying QRCodeGroup entities.
type QRCodeGroupQuery struct {
	config
	ctx         *QueryContext
	order       []qrcodegroup.OrderOption
	inters      []Interceptor
	predicates  []predicate.QRCodeGroup
	withQrcodes *QRCodeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the QRCodeGroupQuery builder.
func (qcgq *QRCodeGroupQuery) Where(ps ...predicate.QRCodeGroup) *QRCodeGroupQuery {
	qcgq.predicates = append(qcgq.predicates, ps...)
	return qcgq
}

// Limit the number of records to be returned by this query.
func (qcgq *QRCodeGroupQuery) Limit(limit int) *QRCodeGroupQuery {
	qcgq.ctx.Limit = &limit
	return qcgq
}

// Offset to start from.
func (qcgq *QRCodeGroupQuery) Offset(offset int) *QRCodeGroupQuery {
	qcgq.ctx.Offset = &offset
	return qcgq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (qcgq *QRCodeGroupQuery) Unique(unique bool) *QRCodeGroupQuery {
	qcgq.ctx.Unique = &unique
	return qcgq
}

// Order specifies how the records should be ordered.
func (qcgq *QRCodeGroupQuery) Order(o ...qrcodegroup.OrderOption) *QRCodeGroupQuery {
	qcgq.order = append(qcgq.order, o...)
	return qcgq
}

// QueryQrcodes chains the current query on the "qrcodes" edge.
func (qcgq *QRCodeGroupQuery) QueryQrcodes() *QRCodeQuery {
	query := (&QRCodeClient{config: qcgq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := qcgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := qcgq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(qrcodegroup.Table, qrcodegroup.FieldID, selector),
			sqlgraph.To(qrcode.Table, qrcode.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, qrcodegroup.QrcodesTable, qrcodegroup.QrcodesColumn),
		)
		fromU = sqlgraph.SetNeighbors(qcgq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first QRCodeGroup entity from the query.
// Returns a *NotFoundError when no QRCodeGroup was found.
func (qcgq *QRCodeGroupQuery) First(ctx context.Context) (*QRCodeGroup, error) {
	nodes, err := qcgq.Limit(1).All(setContextOp(ctx, qcgq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{qrcodegroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (qcgq *QRCodeGroupQuery) FirstX(ctx context.Context) *QRCodeGroup {
	node, err := qcgq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first QRCodeGroup ID from the query.
// Returns a *NotFoundError when no QRCodeGroup ID was found.
func (qcgq *QRCodeGroupQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = qcgq.Limit(1).IDs(setContextOp(ctx, qcgq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{qrcodegroup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (qcgq *QRCodeGroupQuery) FirstIDX(ctx context.Context) int {
	id, err := qcgq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single QRCodeGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one QRCodeGroup entity is found.
// Returns a *NotFoundError when no QRCodeGroup entities are found.
func (qcgq *QRCodeGroupQuery) Only(ctx context.Context) (*QRCodeGroup, error) {
	nodes, err := qcgq.Limit(2).All(setContextOp(ctx, qcgq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{qrcodegroup.Label}
	default:
		return nil, &NotSingularError{qrcodegroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (qcgq *QRCodeGroupQuery) OnlyX(ctx context.Context) *QRCodeGroup {
	node, err := qcgq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only QRCodeGroup ID in the query.
// Returns a *NotSingularError when more than one QRCodeGroup ID is found.
// Returns a *NotFoundError when no entities are found.
func (qcgq *QRCodeGroupQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = qcgq.Limit(2).IDs(setContextOp(ctx, qcgq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{qrcodegroup.Label}
	default:
		err = &NotSingularError{qrcodegroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (qcgq *QRCodeGroupQuery) OnlyIDX(ctx context.Context) int {
	id, err := qcgq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of QRCodeGroups.
func (qcgq *QRCodeGroupQuery) All(ctx context.Context) ([]*QRCodeGroup, error) {
	ctx = setContextOp(ctx, qcgq.ctx, ent.OpQueryAll)
	if err := qcgq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*QRCodeGroup, *QRCodeGroupQuery]()
	return withInterceptors[[]*QRCodeGroup](ctx, qcgq, qr, qcgq.inters)
}

// AllX is like All, but panics if an error occurs.
func (qcgq *QRCodeGroupQuery) AllX(ctx context.Context) []*QRCodeGroup {
	nodes, err := qcgq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of QRCodeGroup IDs.
func (qcgq *QRCodeGroupQuery) IDs(ctx context.Context) (ids []int, err error) {
	if qcgq.ctx.Unique == nil && qcgq.path != nil {
		qcgq.Unique(true)
	}
	ctx = setContextOp(ctx, qcgq.ctx, ent.OpQueryIDs)
	if err = qcgq.Select(qrcodegroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (qcgq *QRCodeGroupQuery) IDsX(ctx context.Context) []int {
	ids, err := qcgq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (qcgq *QRCodeGroupQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, qcgq.ctx, ent.OpQueryCount)
	if err := qcgq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, qcgq, querierCount[*QRCodeGroupQuery](), qcgq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (qcgq *QRCodeGroupQuery) CountX(ctx context.Context) int {
	count, err := qcgq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (qcgq *QRCodeGroupQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, qcgq.ctx, ent.OpQueryExist)
	switch _, err := qcgq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (qcgq *QRCodeGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := qcgq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the QRCodeGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (qcgq *QRCodeGroupQuery) Clone() *QRCodeGroupQuery {
	if qcgq == nil {
		return nil
	}
	return &QRCodeGroupQuery{
		config:      qcgq.config,
		ctx:         qcgq.ctx.Clone(),
		order:       append([]qrcodegroup.OrderOption{}, qcgq.order...),
		inters:      append([]Interceptor{}, qcgq.inters...),
		predicates:  append([]predicate.QRCodeGroup{}, qcgq.predicates...),
		withQrcodes: qcgq.withQrcodes.Clone(),
		// clone intermediate query.
		sql:  qcgq.sql.Clone(),
		path: qcgq.path,
	}
}

// WithQrcodes tells the query-builder to eager-load the nodes that are connected to
// the "qrcodes" edge. The optional arguments are used to configure the query builder of the edge.
func (qcgq *QRCodeGroupQuery) WithQrcodes(opts ...func(*QRCodeQuery)) *QRCodeGroupQuery {
	query := (&QRCodeClient{config: qcgq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	qcgq.withQrcodes = query
	return qcgq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.QRCodeGroup.Query().
//		GroupBy(qrcodegroup.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (qcgq *QRCodeGroupQuery) GroupBy(field string, fields ...string) *QRCodeGroupGroupBy {
	qcgq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &QRCodeGroupGroupBy{build: qcgq}
	grbuild.flds = &qcgq.ctx.Fields
	grbuild.label = qrcodegroup.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.QRCodeGroup.Query().
//		Select(qrcodegroup.FieldName).
//		Scan(ctx, &v)
func (qcgq *QRCodeGroupQuery) Select(fields ...string) *QRCodeGroupSelect {
	qcgq.ctx.Fields = append(qcgq.ctx.Fields, fields...)
	sbuild := &QRCodeGroupSelect{QRCodeGroupQuery: qcgq}
	sbuild.label = qrcodegroup.Label
	sbuild.flds, sbuild.scan = &qcgq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a QRCodeGroupSelect configured with the given aggregations.
func (qcgq *QRCodeGroupQuery) Aggregate(fns ...AggregateFunc) *QRCodeGroupSelect {
	return qcgq.Select().Aggregate(fns...)
}

func (qcgq *QRCodeGroupQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range qcgq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, qcgq); err != nil {
				return err
			}
		}
	}
	for _, f := range qcgq.ctx.Fields {
		if !qrcodegroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if qcgq.path != nil {
		prev, err := qcgq.path(ctx)
		if err != nil {
			return err
		}
		qcgq.sql = prev
	}
	return nil
}

func (qcgq *QRCodeGroupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*QRCodeGroup, error) {
	var (
		nodes       = []*QRCodeGroup{}
		_spec       = qcgq.querySpec()
		loadedTypes = [1]bool{
			qcgq.withQrcodes != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*QRCodeGroup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &QRCodeGroup{config: qcgq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, qcgq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := qcgq.withQrcodes; query != nil {
		if err := qcgq.loadQrcodes(ctx, query, nodes,
			func(n *QRCodeGroup) { n.Edges.Qrcodes = []*QRCode{} },
			func(n *QRCodeGroup, e *QRCode) { n.Edges.Qrcodes = append(n.Edges.Qrcodes, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (qcgq *QRCodeGroupQuery) loadQrcodes(ctx context.Context, query *QRCodeQuery, nodes []*QRCodeGroup, init func(*QRCodeGroup), assign func(*QRCodeGroup, *QRCode)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*QRCodeGroup)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(qrcode.FieldGroupID)
	}
	query.Where(predicate.QRCode(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(qrcodegroup.QrcodesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.GroupID
		if fk == nil {
			return fmt.Errorf(`foreign-key "group_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "group_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (qcgq *QRCodeGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := qcgq.querySpec()
	_spec.Node.Columns = qcgq.ctx.Fields
	if len(qcgq.ctx.Fields) > 0 {
		_spec.Unique = qcgq.ctx.Unique != nil && *qcgq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, qcgq.driver, _spec)
}

func (qcgq *QRCodeGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(qrcodegroup.Table, qrcodegroup.Columns, sqlgraph.NewFieldSpec(qrcodegroup.FieldID, field.TypeInt))
	_spec.From = qcgq.sql
	if unique := qcgq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if qcgq.path != nil {
		_spec.Unique = true
	}
	if fields := qcgq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, qrcodegroup.FieldID)
		for i := range fields {
			if fields[i] != qrcodegroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := qcgq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := qcgq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := qcgq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := qcgq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (qcgq *QRCodeGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(qcgq.driver.Dialect())
	t1 := builder.Table(qrcodegroup.Table)
	columns := qcgq.ctx.Fields
	if len(columns) == 0 {
		columns = qrcodegroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if qcgq.sql != nil {
		selector = qcgq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if qcgq.ctx.Unique != nil && *qcgq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range qcgq.predicates {
		p(selector)
	}
	for _, p := range qcgq.order {
		p(selector)
	}
	if offset := qcgq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := qcgq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// QRCodeGroupGroupBy is the group-by builder for QRCodeGroup entities.
type QRCodeGroupGroupBy struct {
	selector
	build *QRCodeGroupQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (qcggb *QRCodeGroupGroupBy) Aggregate(fns ...AggregateFunc) *QRCodeGroupGroupBy {
	qcggb.fns = append(qcggb.fns, fns...)
	return qcggb
}

// Scan applies the selector query and scans the result into the given value.
func (qcggb *QRCodeGroupGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, qcggb.build.ctx, ent.OpQueryGroupBy)
	if err := qcggb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QRCodeGroupQuery, *QRCodeGroupGroupBy](ctx, qcggb.build, qcggb, qcggb.build.inters, v)
}

func (qcggb *QRCodeGroupGroupBy) sqlScan(ctx context.Context, root *QRCodeGroupQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(qcggb.fns))
	for _, fn := range qcggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*qcggb.flds)+len(qcggb.fns))
		for _, f := range *qcggb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*qcggb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qcggb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// QRCodeGroupSelect is the builder for selecting fields of QRCodeGroup entities.
type QRCodeGroupSelect struct {
	*QRCodeGroupQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (qcgs *QRCodeGroupSelect) Aggregate(fns ...AggregateFunc) *QRCodeGroupSelect {
	qcgs.fns = append(qcgs.fns, fns...)
	return qcgs
}

// Scan applies the selector query and scans the result into the given value.
func (qcgs *QRCodeGroupSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, qcgs.ctx, ent.OpQuerySelect)
	if err := qcgs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QRCodeGroupQuery, *QRCodeGroupSelect](ctx, qcgs.QRCodeGroupQuery, qcgs, qcgs.inters, v)
}

func (qcgs *QRCodeGroupSelect) sqlScan(ctx context.Context, root *QRCodeGroupQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(qcgs.fns))
	for _, fn := range qcgs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*qcgs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qcgs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
