// Code generated by ent, DO NOT EDIT.

package ent

import (
	"qr_backend/ent/filereference"
	"qr_backend/ent/qrcode"
	"qr_backend/ent/qrcodeanalytics"
	"qr_backend/ent/qrcodegroup"
	"qr_backend/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	filereferenceFields := schema.FileReference{}.Fields()
	_ = filereferenceFields
	// filereferenceDescFilename is the schema descriptor for filename field.
	filereferenceDescFilename := filereferenceFields[0].Descriptor()
	// filereference.FilenameValidator is a validator for the "filename" field. It is called by the builders before save.
	filereference.FilenameValidator = filereferenceDescFilename.Validators[0].(func(string) error)
	// filereferenceDescURL is the schema descriptor for url field.
	filereferenceDescURL := filereferenceFields[1].Descriptor()
	// filereference.URLValidator is a validator for the "url" field. It is called by the builders before save.
	filereference.URLValidator = filereferenceDescURL.Validators[0].(func(string) error)
	qrcodeFields := schema.QRCode{}.Fields()
	_ = qrcodeFields
	// qrcodeDescType is the schema descriptor for type field.
	qrcodeDescType := qrcodeFields[0].Descriptor()
	// qrcode.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	qrcode.TypeValidator = qrcodeDescType.Validators[0].(func(string) error)
	// qrcodeDescTitle is the schema descriptor for title field.
	qrcodeDescTitle := qrcodeFields[1].Descriptor()
	// qrcode.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	qrcode.TitleValidator = qrcodeDescTitle.Validators[0].(func(string) error)
	// qrcodeDescCreatedAt is the schema descriptor for created_at field.
	qrcodeDescCreatedAt := qrcodeFields[6].Descriptor()
	// qrcode.DefaultCreatedAt holds the default value on creation for the created_at field.
	qrcode.DefaultCreatedAt = qrcodeDescCreatedAt.Default.(func() time.Time)
	// qrcodeDescUpdatedAt is the schema descriptor for updated_at field.
	qrcodeDescUpdatedAt := qrcodeFields[7].Descriptor()
	// qrcode.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	qrcode.DefaultUpdatedAt = qrcodeDescUpdatedAt.Default.(func() time.Time)
	// qrcode.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	qrcode.UpdateDefaultUpdatedAt = qrcodeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// qrcodeDescAnalytics is the schema descriptor for analytics field.
	qrcodeDescAnalytics := qrcodeFields[9].Descriptor()
	// qrcode.DefaultAnalytics holds the default value on creation for the analytics field.
	qrcode.DefaultAnalytics = qrcodeDescAnalytics.Default.(bool)
	// qrcodeDescActive is the schema descriptor for active field.
	qrcodeDescActive := qrcodeFields[10].Descriptor()
	// qrcode.DefaultActive holds the default value on creation for the active field.
	qrcode.DefaultActive = qrcodeDescActive.Default.(bool)
	qrcodeanalyticsFields := schema.QRCodeAnalytics{}.Fields()
	_ = qrcodeanalyticsFields
	// qrcodeanalyticsDescScannedAt is the schema descriptor for scanned_at field.
	qrcodeanalyticsDescScannedAt := qrcodeanalyticsFields[4].Descriptor()
	// qrcodeanalytics.DefaultScannedAt holds the default value on creation for the scanned_at field.
	qrcodeanalytics.DefaultScannedAt = qrcodeanalyticsDescScannedAt.Default.(func() time.Time)
	qrcodegroupFields := schema.QRCodeGroup{}.Fields()
	_ = qrcodegroupFields
	// qrcodegroupDescName is the schema descriptor for name field.
	qrcodegroupDescName := qrcodegroupFields[0].Descriptor()
	// qrcodegroup.NameValidator is a validator for the "name" field. It is called by the builders before save.
	qrcodegroup.NameValidator = qrcodegroupDescName.Validators[0].(func(string) error)
	// qrcodegroupDescCreatedAt is the schema descriptor for created_at field.
	qrcodegroupDescCreatedAt := qrcodegroupFields[2].Descriptor()
	// qrcodegroup.DefaultCreatedAt holds the default value on creation for the created_at field.
	qrcodegroup.DefaultCreatedAt = qrcodegroupDescCreatedAt.Default.(func() time.Time)
	// qrcodegroupDescUpdatedAt is the schema descriptor for updated_at field.
	qrcodegroupDescUpdatedAt := qrcodegroupFields[3].Descriptor()
	// qrcodegroup.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	qrcodegroup.DefaultUpdatedAt = qrcodegroupDescUpdatedAt.Default.(func() time.Time)
	// qrcodegroup.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	qrcodegroup.UpdateDefaultUpdatedAt = qrcodegroupDescUpdatedAt.UpdateDefault.(func() time.Time)
}
