// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// FileReference is the predicate function for filereference builders.
type FileReference func(*sql.Selector)

// QRCode is the predicate function for qrcode builders.
type QRCode func(*sql.Selector)

// QRCodeAnalytics is the predicate function for qrcodeanalytics builders.
type QRCodeAnalytics func(*sql.Selector)

// QRCodeGroup is the predicate function for qrcodegroup builders.
type QRCodeGroup func(*sql.Selector)
